# Generated by Django 4.0.3 on 2022-07-19 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('day', models.CharField(max_length=50)),
                ('paid', models.BooleanField()),
            ],
        ),
    ]
